### ISSUE TITLE
Phase 3: TO DO

### ISSUE THREAD

**Issue by vpopovic003** [keen003/plus50x#3]
- [x] 1. PROGRESS TRACKING
    - [x] 1.1 Log in feature
        - [x] Create database for users and passwords
        - [x] Deploy database on Heroku
    - [x] 1.2 Tracking logic (code)
    - [x] 1.3 ~~Landing page displays tracking~~ Added different page

- [x] 2. Dark theme
    - [x] 2.1 Dark theme button

- [x]  3. Cookie checker

**Comment by constantinktz** [comment]
Everything should work
