### ISSUE TITLE
"Video" link in lower menu on desktop version links to mobile page

### ISSUE THREAD

**Issue by vpopovic003** [keen003/plus50x#4]
There are two files: lectures.html and video.html.

lecture.html is opened by default when clicking on a particular week. In desktop version it opens up video right away, but in mobile it opens only a menu. 'video' link then links to video.html for mobile version, but it is doing the same thing on the desktop version, which is false. The page looks different.

Possibilities: 
1. either make video.html same as lectures.html so that it does not look different on desktop version (this creates duplicate code)
2. line 14 in lectures.html: make this link point to video.html on mobile version, but point to lectures.html on desktop version (if possible)

**Comment by constantinktz** [comment]
Just deleted it for bigger screens
