### ISSUE TITLE
Wrong formatting of example code in notes

### ISSUE THREAD

**Issue by vpopovic003** [keen003/plus50x#6]
In notes.html, example code is formatted as:

![example picture](https://cdn.discordapp.com/attachments/999422542559334451/1000130574981267486/unknown.png)

should be:

![example picture](https://cdn.discordapp.com/attachments/999422542559334451/1000131187462918164/unknown.png)

Issues:
- Wrong font because of * selector in style.css
- Indentation not displayed correctly (reason unknown)

**Comment by constantinktz** [comment]
Should be done
