### ISSUE TITLE
Bottom helper menu does not show up on every page

### ISSUE THREAD

**Issue by vpopovic003** [keen003/plus50x#8]
The code for the bottom helper menu is only present on lecture.html, so it gets displayed only on that page.

Should we keep it in desktop version anyway?
If yes, should it be displayed on every page?
If yes, it requires code to be moved from lecture.html to layout.html, but it will mess up mobile version.

**Comment by constantinktz** [comment]
Would only show it on that one page one bigger screens

**Comment by constantinktz** [comment]
No other idea yet
